### ISSUE TITLE
Error: EXDEV: cross-device link not permitted, rename

### ISSUE THREAD

**Issue by DiscRisknBisque** [trufflesuite/truffle-box#4]
From @davekaj:

does anyone know how to fix this? full error looks like so:

$ truffle unbox react
Downloading...
events.js:163
throw er; // Unhandled 'error' event
^

Error: EXDEV: cross-device link not permitted, rename '/home/davekaj/Desktop/Crypto-Dev/truffle/truffle-react-box/1499396196726-8478197198597666/react-box-master' -> '/tmp/tmp-8865HTmCImGeZVr'

Running Ubuntu

**Comment by gnidan** [comment]
This should be fixed in Truffle v3.4.5
